services:
  - type: web
    name: portfolio-rishikesh-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://portfolio-rishikesh-backend.vercel.app